// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"crypto/tls"
	"github.com/Lajule/objects-service/pkg/service"
	"github.com/Lajule/objects-service/pkg/store"
	"go.uber.org/zap"
	"net"
)

// Injectors from wire.go:

func InitializeService(basePath string, memory bool, tcpAddr *net.TCPAddr, tlsConfig *tls.Config, logger *zap.Logger) *service.Service {
	storeStore := store.NewStore(basePath, memory, logger)
	serviceService := service.NewService(tcpAddr, tlsConfig, storeStore, logger)
	return serviceService
}
